- name : Install MySQL Server
  ansible.builtin.dnf :
    name : mysql-server
    state: latest
- name : Start and Enable mysqld service
  ansible.builtin.systemd_service :
    name : mysqld
    state: started
    enabled : yes

- name : Install MySQL Client
  ansible.builtin.dnf :
   name : mysql
   state : latest

- name : Connect MySQL Server
  ansible.builtin.command : "mysql -h {{hostname}} -u{{mysqluser}} -p{{mysqlpassword}}"
  register : SqlStatus
  ignore_erros : yes

- name : Print SqlStatus
  ansible.builtin.debug:
   msg : "{{SqlStatus}}"