- name : Install MySQL Server
  ansible.builtin.dnf :
    name : mysql-server
    state: latest
- name : Start and Enable mysqld service
  ansible.builtin.systemd_service :
    name : mysqld
    state: started
    enabled : yes

- name : Install PyMysql Client
  ansible.builtin.pip :
   name : "{{item}}"
   state : latest
   executable : pip3.9
  loop :
   - PyMySQL
   - cryptography

- name : Connect MySQL Server
  community.mysql.mysql_info : 
   login_user : "{{mysqluser}}"
   login_password : "{{mysqlpassword}}"
   login_host :  "{{hostname}}"
   filter : version
  register : SqlStatus
  ignore_errors : true

- name : Print SqlStatus
  ansible.builtin.debug:
   msg : "{{SqlStatus}}"